Repository Team-Ampersand/HoneyPot-Client, pull requests merged in 2024-02, with the labels that each got.

#5 [#5] 회원가입 로직을 구현했습니다.
  .github/ISSUE_TEMPLATE/PULL_REQUEST_TEMPLATE.md
  package.json
  src/components/Signup/index.jsx
  src/components/Signup/style.jsx
  yarn.lock
Labels: 2️⃣ Priortiy: Medium, ✨ Type: Feature, 📬 Type: API

#6 .github 파일 수정했어요!
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/PULL_REQUEST_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/feature.yml
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ⚙ Type: Setting, 📄 Type: Docs

#7 [#7] 글쓰기 페이지를 퍼블리싱 했습니다.
  src/App.js
  src/asset/svg/AddBoldStyleText.jsx
  src/asset/svg/AddDevText.jsx
  src/asset/svg/AddH1Text.jsx
  src/asset/svg/AddH2Text.jsx
  src/asset/svg/AddH3Text.jsx
  src/asset/svg/AddH4Text.jsx
  src/asset/svg/AddImg.jsx
  src/asset/svg/AddItalicText.jsx
  src/asset/svg/AddLinkText.jsx
  src/asset/svg/AddTextMiddleline.jsx
  src/asset/svg/OptionLine.jsx
  src/components/Writing/index.jsx
  src/components/Writing/style.jsx
  src/public/components/Header/style.jsx
Labels: 🎨 Type: Publishing

#10 [#10] 글 쓰기 페이지를 로직 구현 했습니다.
  src/components/Writing/index.jsx
  src/components/Writing/style.js
Labels: 1️⃣ Priority: High, ✨ Type: Feature, 📬 Type: API

#11 [#11] 썸네일 업로드 페이지를 퍼블리싱 했습니다
  src/App.js
  src/asset/svg/ThumbnailImg.jsx
  src/asset/svg/index.js
  src/components/Thumbnail/index.jsx
  src/components/Thumbnail/style.js
  src/components/index.js
Labels: 1️⃣ Priority: High, 🎨 Type: Publishing

#12 [#12] 썸네일 페이지의 로직을 구현했어요
  src/components/Thumbnail/index.jsx
  src/components/Thumbnail/style.js
  src/components/Writing/index.jsx
Labels: ✨ Type: Feature, 📬 Type: API

#13 [#13] 회원가입 로직을 api에 맞게 수정함
  src/components/Signup/index.jsx
Labels: ⚡Type: Simple, 📬 Type: API

#14 [#14] 로그인 로직을 완성했습니다.
  src/apis/TokenManager.js
  src/apis/refresh.js
  src/components/Signin/index.jsx
  src/components/Signin/style.js
  src/components/Thumbnail/index.jsx
  src/components/Writing/index.jsx
  src/utils/Storages.js
Labels: ✨ Type: Feature, 📬 Type: API

#15 [#15] API URL 변경
  src/apis/TokenManager.js
  src/apis/refresh.js
  src/components/Signin/index.jsx
  src/components/Signup/index.jsx
  src/components/Thumbnail/index.jsx
  src/components/Writing/index.jsx
Labels: 📬 Type: API

#16 [#16] 메인 페이지 퍼블리싱
  src/asset/svg/CommentIcon.jsx
  src/asset/svg/CurrentWindowIcon.jsx
  src/asset/svg/LikeButtonIcon.jsx
  src/asset/svg/LikeCountIcon.jsx
  src/asset/svg/NextWindowIcon.jsx
  src/asset/svg/ProfileIcon.jsx
  src/asset/svg/WriteButton.jsx
  src/asset/svg/index.js
  src/components/Main/index.jsx
  src/components/Main/style.js
Labels: 1️⃣ Priority: High, 🎨 Type: Publishing
